/**
 * ==============================================================================
 * @scope4/agent — report.ts
 * Member C — AI + Analytics Lead
 *
 * ReportGenerationAgent: uses Gemini 1.5 Flash to generate a professional
 * CBAM compliance report in Markdown from structured calculation results.
 *
 * Key design rules enforced via system prompt:
 *   - CBAM Compliance section uses ONLY cbam_embedded_tco2 and cbam_exposure_eur
 *   - Carbon Footprint Overview section uses transport_tco2 and portfolio_carbon_tco2
 *   - The two sections are NEVER mixed (EU Reg 2023/956 compliance)
 *   - A local fallback report is generated if the LLM call fails
 * ==============================================================================
 */

import type { ComplianceBundle, ValidationResult, CalculationResult } from '@scope4/types'
import { GoogleGenerativeAI } from '@google/generative-ai'

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY ?? '')
const model = genAI.getGenerativeModel({ model: 'gemini-2.5-flash' })

const SYSTEM_PROMPT = `You are a professional CBAM (Carbon Border Adjustment Mechanism) compliance analyst.
You receive a structured JSON object with verified shipment data and calculation results.
Your task is to write a professional, readable compliance report in Markdown that can replace old-school official papers.

CRITICAL LEGAL ACCURACY RULES:
1. Do NOT invent, estimate, or change any numerical values. Use ONLY the numbers provided.
2. Your report MUST follow the STRICT TEMPLATE below. Do not deviate from this structure.
3. In the CBAM Compliance section, use cbam_embedded_tco2 as the CBAM certificate obligation base, and cbam_exposure_eur as the estimated cost.
4. In the Carbon Footprint Overview section, use transport_tco2 and portfolio_carbon_tco2.
5. Identify which data came from the seller, importer, and logistics partner. Flag validation issues with ⚠️ warnings.
6. Use professional, official compliance language (avoid marketing or advertising tone).

--- STRICT TEMPLATE TO FOLLOW ---
# Scope4 Official CBAM Compliance Report
**Trade ID:** [Insert Trade ID]
**Date of Generation:** [Insert Date]

## Statement of Purpose
This document is generated by the Scope4 Compliance Infrastructure for the purpose of regulatory carbon accounting under the European Union Carbon Border Adjustment Mechanism (Regulation (EU) 2023/956). It carries the value of a verified, multi-party attestation trail and is intended for use by customs authorities, compliance auditors, and internal risk teams.

## Methodology (Blockchain & AI Verification)
The data within this report is secured via the Solana blockchain, ensuring cryptographic immutability, auditability, and decentralization of all party attestations. Furthermore, cross-party data validation is performed by independent, deterministic AI agents. This ensures absolute neutrality without favoring the seller or importer, thereby creating cryptographically-backed trust.

## 1. Parties and Attestations
[List the seller, importer, and logistics data, including validation results, data quality flags, and confidence level]

## 2. CBAM Compliance (Regulatory Liability)
> Note: CBAM liability covers ONLY production-embedded emissions. Transport emissions are explicitly excluded from this obligation.

- **CBAM-Liable Embedded Emissions:** [X] tCO₂
- **Estimated CBAM Certificate Obligation:** €[X] 
*(Note: Uses a placeholder certificate price of €50/tCO₂. Real CBAM uses EUA market price at time of declaration.)*

## 3. Carbon Footprint Overview (Internal Analytics)
> Note: The following metrics are for Business Intelligence (BI) and internal ESG reporting only. They are NOT CBAM-liable amounts.

- **Transport / Logistics Emissions:** [X] tCO₂
- **Total Portfolio Carbon Footprint:** [X] tCO₂

## 4. Audit Trail & Signatures
All data inputs have been verified and sealed on-chain. Refer to the specific transaction signatures (Tx) on the Solana Explorer for cryptographic proof of attestation.

**Authorized Signature:**
*Scope4 Automated Compliance Agent*
*(Cryptographically sealed by Scope4 Infrastructure)*
--- END TEMPLATE ---

Output only the filled Markdown template. No preamble or meta-commentary.`

export async function generateReport(
  bundle: ComplianceBundle,
  validation: ValidationResult,
  calc: CalculationResult
): Promise<string> {
  const inputPayload = {
    trade_id: bundle.trade_id,
    bundle_status: bundle.bundle_status,
    timestamps: {
      seller_attested:    bundle.seller_attested_at,
      importer_attested:  bundle.importer_attested_at,
      logistics_attested: bundle.logistics_attested_at,
      bundle_ready:       bundle.ready_at,
    },
    validation: {
      passed:     validation.passed,
      flags:      validation.flags,
      confidence: validation.confidence,
    },
    cbam_reporting_layer: {
      // These are the ONLY figures that belong in the CBAM certificate obligation
      cbam_embedded_tco2:              calc.cbam_embedded_tco2,
      cbam_exposure_eur_estimate:      calc.cbam_exposure_eur,
      certificate_price_used_eur_per_tco2: 50,
      price_note: 'Placeholder. Real CBAM uses EUA market price at time of declaration.',
    },
    business_intelligence_layer: {
      // These figures extend the picture but are NOT part of the CBAM obligation
      transport_tco2:        calc.transport_tco2,
      portfolio_carbon_tco2: calc.portfolio_carbon_tco2,
      distance_km:           calc.distance_km,
      note: 'Transport emissions shown for internal carbon-footprint analytics only.',
    },
    data_quality: {
      intensity_source:        calc.intensity_source,
      intensity_value_tco2_per_t: calc.intensity_value_used,
      confidence:              calc.confidence,
      confidence_notes:        calc.confidence_notes,
    },
    audit_note:
      'All attestations recorded on Solana Devnet. Tx signatures available on bundle detail page.',
  }

  const prompt = `${SYSTEM_PROMPT}\n\nInput data:\n\`\`\`json\n${JSON.stringify(inputPayload, null, 2)}\n\`\`\``

  try {
    const result = await model.generateContent(prompt)
    const text = result.response.text()
    if (!text || text.length < 100) {
      throw new Error('LLM returned empty or too-short report')
    }
    return text
  } catch (err) {
    console.error('[ReportAgent] LLM call failed, using fallback:', err)
    return generateFallbackReport(bundle.trade_id, calc)
  }
}

// ─── Local fallback (used when Gemini API is unavailable) ─────────────────────

function generateFallbackReport(trade_id: string, calc: CalculationResult): string {
  const date = new Date().toISOString().split('T')[0];
  return `# Scope4 Official CBAM Compliance Report
**Trade ID:** ${trade_id}
**Date of Generation:** ${date}

## Statement of Purpose
This document is generated by the Scope4 Compliance Infrastructure for the purpose of regulatory carbon accounting under the European Union Carbon Border Adjustment Mechanism (Regulation (EU) 2023/956). It carries the value of a verified, multi-party attestation trail and is intended for use by customs authorities, compliance auditors, and internal risk teams.

## Methodology (Blockchain & AI Verification)
The data within this report is secured via the Solana blockchain, ensuring cryptographic immutability, auditability, and decentralization of all party attestations. Furthermore, cross-party data validation is performed by independent, deterministic AI agents. This ensures absolute neutrality without favoring the seller or importer, thereby creating cryptographically-backed trust.

## 1. Parties and Attestations
This report covers a shipment processed through the Scope4 compliance platform. All three parties (seller, importer, logistics) have attested their respective data on Solana Devnet.
- Intensity source: **${calc.intensity_source}**
- Confidence: **${calc.confidence}**
${calc.confidence_notes.length > 0 ? calc.confidence_notes.map(n => `- ⚠️ ${n}`).join('\n') : '- No quality flags raised.'}

## 2. CBAM Compliance (Regulatory Liability)
> Note: CBAM liability covers ONLY production-embedded emissions. Transport emissions are explicitly excluded from this obligation.

- **CBAM-Liable Embedded Emissions:** ${calc.cbam_embedded_tco2.toFixed(2)} tCO₂
- **Estimated CBAM Certificate Obligation:** €${calc.cbam_exposure_eur.toFixed(2)}
*(Note: Uses a placeholder certificate price of €50/tCO₂. Real CBAM uses EUA market price at time of declaration.)*

## 3. Carbon Footprint Overview (Internal Analytics)
> Note: The following metrics are for Business Intelligence (BI) and internal ESG reporting only. They are NOT CBAM-liable amounts.

- **Transport / Logistics Emissions:** ${calc.transport_tco2.toFixed(2)} tCO₂ _(${calc.distance_km} km)_
- **Total Portfolio Carbon Footprint:** ${calc.portfolio_carbon_tco2.toFixed(2)} tCO₂

## 4. Audit Trail & Signatures
All data inputs have been verified and sealed on-chain. Refer to the specific transaction signatures (Tx) on the Solana Explorer for cryptographic proof of attestation.

**Authorized Signature:**
*Scope4 Automated Compliance Agent*
*(Cryptographically sealed by Scope4 Infrastructure)*`
}
