'use client'
import { useParams, useRouter } from 'next/navigation'
import useSWR from 'swr'
import { apiGet } from '@/lib/api'
import type { BundleDetailResponse } from '@scope4/types'
import ReactMarkdown from 'react-markdown'
import styles from './page.module.css'

export default function ReportPage() {
  const params = useParams()
  const router = useRouter()
  const id = params?.id as string

  // Using bundle detail response which contains the report and all attestations
  const { data, isLoading } = useSWR<BundleDetailResponse>(
    id ? `/api/reports/${id}` : null,
    (url: string) => apiGet(url)
  )

  if (isLoading || !data) {
    return <div className={styles.loadingContainer}>Loading report data...</div>
  }

  const { report, bundle, seller, trade, logistics } = data

  if (!report) {
    return <div className={styles.errorContainer}>Report not generated yet or not found.</div>
  }

  const confidenceColor = report.confidence_level === 'high' ? 'var(--accent-green)' : 
                          report.confidence_level === 'medium' ? 'var(--accent-amber)' : 'var(--accent-red)'

  return (
    <div className={styles.container}>
      <button className="btn btn-secondary btn-sm" onClick={() => router.back()} style={{ marginBottom: 24 }}>
        ← Back to Bundle
      </button>

      <div className={styles.headerRow}>
        <div>
          <h1 className="text-3xl font-extrabold">Compliance Report</h1>
          <p className="text-secondary">Trade ID: {bundle.trade_id}</p>
        </div>
        <div className={styles.confidenceBadge} style={{ borderColor: confidenceColor, color: confidenceColor, backgroundColor: `color-mix(in srgb, ${confidenceColor} 10%, transparent)` }}>
          {report.confidence_level.toUpperCase()} CONFIDENCE
        </div>
      </div>

      <div className="grid-2" style={{ gap: 24, marginBottom: 32 }}>
        {/* CBAM Summary Card */}
        <div className={`card ${styles.cbamSection}`}>
          <div className={styles.sectionLabel}>CBAM Reporting Layer</div>
          <p className="text-sm text-secondary" style={{ marginBottom: 16 }}>Regulatory scope (EU Reg 2023/956)</p>
          <div className={styles.metricsGrid}>
            <div>
              <div className="text-xs font-semibold text-secondary">Embedded Emissions</div>
              <div className="text-2xl font-bold" style={{ color: 'var(--text-primary)' }}>{report.cbam_embedded_tco2.toFixed(1)} <span className="text-sm">tCO₂</span></div>
            </div>
            <div>
              <div className="text-xs font-semibold text-secondary">Est. Exposure (€50/t)</div>
              <div className="text-2xl font-bold" style={{ color: 'var(--accent-amber)' }}>€{report.cbam_exposure_eur.toFixed(0)}</div>
            </div>
          </div>
        </div>

        {/* BI Summary Card */}
        <div className={`card ${styles.biSection}`}>
          <div className={styles.sectionLabel}>Business Intelligence Layer</div>
          <p className="text-sm text-secondary" style={{ marginBottom: 16 }}>Internal analytics (Not CBAM-liable)</p>
          <div className={styles.metricsGrid}>
            <div>
              <div className="text-xs font-semibold text-secondary">Transport Emissions</div>
              <div className="text-2xl font-bold" style={{ color: 'var(--text-primary)' }}>{report.transport_tco2.toFixed(1)} <span className="text-sm">tCO₂</span></div>
            </div>
            <div>
              <div className="text-xs font-semibold text-secondary">Portfolio Carbon</div>
              <div className="text-2xl font-bold" style={{ color: 'var(--accent-blue)' }}>{report.portfolio_carbon_tco2.toFixed(1)} <span className="text-sm">tCO₂</span></div>
            </div>
          </div>
        </div>
      </div>

      <div className="grid-2" style={{ gap: 24 }}>
        {/* Generated Markdown Report */}
        <div className={`card ${styles.reportContent}`}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 24 }}>
            <span style={{ fontSize: 24 }}>🤖</span>
            <span className="text-sm font-semibold" style={{ color: 'var(--accent-green)' }}>Generated by {report.llm_model_used}</span>
          </div>
          <div className={styles.markdownBody}>
            <ReactMarkdown>{report.report_text}</ReactMarkdown>
          </div>
        </div>

        {/* Audit Trail */}
        <div className="card">
          <h3 className="text-lg font-semibold" style={{ marginBottom: 16 }}>Solana Audit Trail</h3>
          <p className="text-sm text-secondary" style={{ marginBottom: 24 }}>All attestations are cryptographically verified on the Solana devnet.</p>
          
          <div className={styles.auditList}>
            {seller && (
              <div className={styles.auditItem}>
                <div className={styles.auditIcon}>🏭</div>
                <div className={styles.auditDetails}>
                  <div className="font-semibold text-sm">Seller Attestation</div>
                  <div className="text-xs text-secondary">{seller.seller_name}</div>
                  <a href={`https://explorer.solana.com/tx/${seller.solana_tx}?cluster=devnet`} target="_blank" rel="noreferrer" className={styles.txLink}>
                    View TX ↗
                  </a>
                </div>
              </div>
            )}
            
            {trade && (
              <div className={styles.auditItem}>
                <div className={styles.auditIcon}>🏢</div>
                <div className={styles.auditDetails}>
                  <div className="font-semibold text-sm">Trade Record</div>
                  <div className="text-xs text-secondary">{trade.importer_name}</div>
                  <a href={`https://explorer.solana.com/tx/${trade.solana_tx}?cluster=devnet`} target="_blank" rel="noreferrer" className={styles.txLink}>
                    View TX ↗
                  </a>
                </div>
              </div>
            )}

            {logistics && (
              <div className={styles.auditItem}>
                <div className={styles.auditIcon}>🚢</div>
                <div className={styles.auditDetails}>
                  <div className="font-semibold text-sm">Logistics Confirmation</div>
                  <div className="text-xs text-secondary">{logistics.logistics_name}</div>
                  <a href={`https://explorer.solana.com/tx/${logistics.solana_tx}?cluster=devnet`} target="_blank" rel="noreferrer" className={styles.txLink}>
                    View TX ↗
                  </a>
                </div>
              </div>
            )}
            
            <div className={styles.auditItem}>
              <div className={styles.auditIcon}>🤖</div>
              <div className={styles.auditDetails}>
                <div className="font-semibold text-sm">AI Agent Report</div>
                <div className="text-xs text-secondary">Scope4 Compliance Agent</div>
                {bundle.solana_bundle_pda && (
                  <div className="text-xs text-secondary" style={{ marginTop: 4 }}>PDA: {bundle.solana_bundle_pda}</div>
                )}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
